api:
  dashboard: false

metrics:
  prometheus:
    addRoutersLabels: true

certificatesResolvers:
  hosting:
    acme:
      email: "29304143+Psycho0verload@users.noreply.github.com"
      storage: "dns_letsencrypt.json"
      dnsChallenge:
        provider: hostingde
        delayBeforeCheck: 0
        
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

global:
  checknewversion: true
  sendanonymoususage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy"
  file:
    filename: "./dynamic_conf.yml"
    watch: true
  providersThrottleDuration: 10s

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100