# Author: Jonathan Starck (jonathan@starck.info)
# traefik.yml (c) 2024
# Desc: description
# Created:  2024-06-05T06:55:10.370Z
# Modified: 2024-06-07T08:38:33.788Z

api:
  dashboard: true

metrics:
  prometheus:
    addRoutersLabels: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

global:
  checknewversion: true
  sendanonymoususage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy"
  file:
    filename: "./dynamic_conf.yml"
    watch: true
  providersThrottleDuration: 10s

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
  
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100